---
- name: Fix root
  hosts: all
  remote_user: centos
  become: true
  tasks:
    - name: Fix user for centos
      ansible.builtin.include_role:
        name: common
        tasks_from: fix-login.yml
