---

- name: include os specific vars
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags:
    - always

- name: "Install common system packages and python dependencies"
  ansible.builtin.import_tasks: packages.yml
  tags:
    - common-packages

- name: "Configure SSHd and root user"
  ansible.builtin.import_tasks: ssh.yml
  tags:
    - common-sshd
  when:
    - configure_ssh | default(True)

- name: "Configure /etc/hosts"
  ansible.builtin.import_tasks: hostfile.yml
  tags:
    - common-hostfile

- name: "Configure system autoupdate parameters"
  ansible.builtin.import_tasks: autoupdate.yml
  tags:
    - common-autoupdate

- name: "Remove cloud-init packages and config files"
  ansible.builtin.import_tasks: cloud_init.yml
  tags:
    - common-cloudinit

- name: "Configure Local Users and Groups"
  ansible.builtin.import_tasks: users.yml
  when:  not openldap_client_enable|default(false)
  tags:
    - common-users

- name: "Configure Sudoers"
  ansible.builtin.import_tasks: sudo.yml
  tags:
    - common-sudoers

- name: "Configure MDNS reflection / Avahi"
  ansible.builtin.import_tasks: mdns_reflection.yml
  when:
    - enable_mdns_reflection | default(False)
  tags:
    - common-mdns

- name: "Configure Serial-over-LAN [Ubuntu]"
  ansible.builtin.import_tasks: ubuntu-sol.yml
  when:
    - ansible_os_family == "Debian"
    - ansible_virtualization_role != "guest"
    - serialtty != None
    - consoletty != None
  tags:
    - common-sol

- name: "Configure Serial-over-LAN [RHEL/CentOS]"
  ansible.builtin.import_tasks: redhat-sol.yml
  when:
    - ansible_os_family == "RedHat"
    - ansible_virtualization_role != "guest"
    - serialtty != None
    - consoletty != None
  tags:
    - common-sol

- name: "Configure Timezone Info"
  community.general.timezone:
    name: "{{ timezone }}"
  tags:
    - common-timezone

- name: "Install Cockpit"
  ansible.builtin.import_tasks: cockpit.yml
  tags:
    - common-cockpit
  when: common_enable_cockpit | default(False)

- name: "Reboot host if grub config was updated"
  ansible.builtin.reboot:
  when: grub_require_rebuild | default(false)
  tags:
    - common-sol
