---
- name: mdns_reflection | Install and configure Avahi
  block:
    - name: Wait for locks
      ansible.builtin.include_tasks:
        file: wait_for_locks.yml

    - name: mdns_reflection | Install Avahi-Daemon package
      ansible.builtin.package:
        name: "{{ common_mdns_pkgs }}"
        state: present

    - name: mdns_reflection | Template Avahi-Daemon configuration
      ansible.builtin.template:
        dest: /etc/avahi/avahi-daemon.conf
        src: avahi-daemon.conf.j2
        owner: root
        group: root
        mode: "0644"
      notify: Restart Avahi
