---
- name: Install Avahi-Daemon package
  ansible.builtin.package:
    name: "{{ common_mdns_pkgs }}"
    state: present
  when:
    - enable_mdns_reflection | default(False)

- name: Template Avahi-Daemon configuration
  ansible.builtin.template:
    dest: /etc/avahi/avahi-daemon.conf
    src: avahi-daemon.conf.j2
    owner: root
    group: root
    mode: "0644"
  register: avahi_config
  when:
    - enable_mdns_reflection | default(False)

- name: Reload Avahi-Daemon configuration on change
  ansible.builtin.systemd:
    name: avahi-daemon.service
    state: restarted
  when:
    - enable_mdns_reflection | default(False)
    - avahi_config is defined
    - avahi_config is changed
