---

- name: Install common packages
  ansible.builtin.apt:
    name: '{{ common_pkgs }}'
    state: present
  when:
    - common_pkgs is defined
    - common_pkgs != None

- name: "Uninstall any unwanted packages managed via OS package-manager"
  ansible.builtin.package:
    name: '{{ common_uninstall_pkgs }}'
    state: absent
  when:
    - common_uninstall_pkgs is defined
    - common_uninstall_pkgs != None

- name: "Install python requirements via Pip"
  ansible.builtin.pip:
    name: "{{ common_python_pkgs }}"
    state: present
  when:
    - common_python_pkgs is defined
    - common_python_pkgs != None
