---

- name: "Allow passwordless sudo for 'admin' group"
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    regexp: '^%admin.*$'
    line: '%admin ALL=(ALL) NOPASSWD:ALL'
    state: present
    backup: true
    validate: 'visudo -cf %s'
